apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: s1-tyler
  region: us-west-1
availabilityZones:
    - us-west-1a
#    - us-west-1b
    - us-west-1c
#    - us-west-1d
nodeGroups:
  - name: worker-group
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ssh:
      publicKeyName: s1-tyler
